# Generated by Django 5.1.2 on 2024-10-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField()),
            ],
            options={
                'db_table': 'usergroups',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('ticketid', models.TextField(blank=True, null=True)),
                ('affectedservice', models.TextField(blank=True, null=True)),
                ('incidentcreated', models.DateTimeField(blank=True, null=True)),
                ('incidentstart', models.DateTimeField(blank=True, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('incidentclosedtime', models.DateTimeField(blank=True, null=True)),
                ('assignedgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.usergroup')),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ticket', to='tickets.incident')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.usergroup')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='assignee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incident', to='tickets.userprofile'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reportedby',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incident', to='tickets.userprofile'),
        ),
    ]
