# Generated by Django 5.1.2 on 2024-10-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='ticketid',
        ),
    ]
