# Generated by Django 5.1.2 on 2024-12-16 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_incident_ticketid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='tickets.userprofile'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reportedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to='tickets.userprofile'),
        ),
    ]
