# Generated by Django 5.1.2 on 2024-12-19 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='affectedservice',
            field=models.TextField(default='Unknown Service'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incidentcreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incidentstart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.TextField(default='Low'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='state',
            field=models.TextField(default='New'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.TextField(default='Untitled Incident'),
        ),
    ]
