# Generated by Django 5.1.2 on 2024-12-19 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='affectedservice',
        ),
        migrations.AddField(
            model_name='incident',
            name='affected_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.service'),
        ),
    ]
