# Generated by Django 5.1.2 on 2024-12-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_remove_incident_affectedservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Operational', 'Operational'), ('Degraded Performance', 'Degraded Performance'), ('Partial Outage', 'Partial Outage'), ('Major Outage', 'Major Outage')], default='Operational', max_length=50),
        ),
    ]
